"""added img_url column to users table

Revision ID: 0abc482a5bc1
Revises: a911b3c0fdc0
Create Date: 2022-08-05 03:34:56.110250

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0abc482a5bc1'
down_revision = 'a911b3c0fdc0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('img_url', sa.String(), server_default='default', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'img_url')
    # ### end Alembic commands ###
