"""init

Revision ID: 4894995cce53
Revises: 
Create Date: 2022-08-05 06:20:24.019408

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4894995cce53'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('faculties',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('department', sa.String(), nullable=False),
    sa.Column('img_url', sa.String(), nullable=False),
    sa.Column('teaching_rate', sa.Numeric(), server_default='0', nullable=False),
    sa.Column('total_teaching_rate', sa.Numeric(), server_default='0', nullable=False),
    sa.Column('marking_rate', sa.Numeric(), server_default='0', nullable=False),
    sa.Column('total_marking_rate', sa.Numeric(), server_default='0', nullable=False),
    sa.Column('assignment_rate', sa.Numeric(), server_default='0', nullable=False),
    sa.Column('total_assignment_rate', sa.Numeric(), server_default='0', nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('img_url', sa.String(), server_default='default', nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('votes',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('faculty_id', sa.Integer(), nullable=False),
    sa.Column('teaching_value', sa.Numeric(), nullable=False),
    sa.Column('marking_value', sa.Numeric(), nullable=False),
    sa.Column('assignment_value', sa.Numeric(), nullable=False),
    sa.ForeignKeyConstraint(['faculty_id'], ['faculties.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'faculty_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('votes')
    op.drop_table('users')
    op.drop_table('faculties')
    # ### end Alembic commands ###
