"""added total_rate to faculties table

Revision ID: e3a32b0cafde
Revises: 0abc482a5bc1
Create Date: 2022-08-05 05:28:13.236944

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e3a32b0cafde'
down_revision = '0abc482a5bc1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('faculties', sa.Column('total_rate', sa.Numeric(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('faculties', 'total_rate')
    # ### end Alembic commands ###
